name: Docker - PR

on:
  workflow_call:
    inputs:
      service_path:
        type: string
        required: false
        default: '.'
      shared_context:
        type: boolean
        required: false
        default: false
        description: Set to true if dockerfile needs repo wide context
      ecr:
        type: boolean
        required: false
        default: false
        description: Set to true if ECR access is required to build
     secrets:
      AWS_ACCESS_KEY_DEVELOPMENT:
        required: false
      AWS_SECRET_ACCESS_KEY_DEVELOPMENT:
        required: false   


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure ECR AWS credentials (dev)
        if: ${{ inputs.ecr }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEVELOPMENT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVELOPMENT }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        if: ${{ inputs.ecr }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ inputs.service_path }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.service_path }}-buildx-

      - name: Shared Context Build
        if: ${{ inputs.shared_context }}
        id: shared_contenxt_docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ inputs.service_path }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build
        if: ${{ ! inputs.shared_context }}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.service_path }}
          file: ./${{ inputs.service_path }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
