name: Java - PR

on:
  workflow_call:
    inputs:
      service_path:
        type: string
        required: false
        default: "."
      java_distribution:
        type: string
        required: true
      java_version:
        type: string
        required: true

jobs:
  pr:
    runs-on: ubuntu-latest
    env:
      MVN_DEFAULT: mvn --settings settings.xml --projects ${{ inputs.service_path }} --also-make
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java_distribution }}
          java-version: ${{ inputs.java_version }}

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: /home/runner/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify
        run: |
          ${{ env.MVN_DEFAULT }} clean compile verify -U -DskipTests

      - name: Unit Test
        run: |
          ${{ env.MVN_DEFAULT }} test --fail-at-end
