name: Revision Update
on:
  workflow_call:
    inputs:
      service_path:
        type: string
        default: '.'
        description: Path of application if a monorepo is in use (used for infrastructure)
        required: false
      commit_id:
        type: string
        required: true
        description: Git Commit
      revision_file:
        type: string
        required: true
        description: Revision file to update
 
jobs:
  revision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write revision to file
        run: |
          cd ${{ inputs.service_path }}
          echo ${{ inputs.commit_id }} > ${{ inputs.revision_file }}

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -a -m "Update revision (run number: ${GITHUB_RUN_NUMBER})"
          git push origin main